[pytest]
addopts = -q
markers =
    smoke
    regression
    etl
    api
    ui
    e2e
    ui: UI tests
    api_smoke: API smoke tests
    ui_smoke: UI smoke tests
    etl_smoke: ETL smoke tests
bdd_features_base_dir = features